-- CREATE TABLE IF NOT EXISTS end_user
--   (
--     id int PRIMARY KEY,
--     username text NULL,
--     password text NULL,
--     email text NOT NULL,
--     email_verified bool NULL,
--     verification_token text NULL,
--     realm text NULL,
--     settings jsonb
--   );
